# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0006_auto_20160227_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieratings_app.Movie')),
            ],
        ),
    ]
