# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0007_newreviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewReviews',
            new_name='NewReview',
        ),
    ]
