# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0008_auto_20160228_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newreview',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='newreview',
            name='movie',
            field=models.TextField(),
        ),
    ]
